= JARiS
:groupId: io.github.oliviercailloux
:artifactId: jaris
:repository: JARiS

image:https://github.com/oliviercailloux/{artifactId}/workflows/Maven%20CI%20workflow/badge.svg["Maven CI", link="https://github.com/oliviercailloux/{repository}/actions"]
image:https://maven-badges.herokuapp.com/maven-central/{groupId}/{artifactId}/badge.svg["Artifact on Maven Central", link="https://central.sonatype.com/search?ga|1%7Cg%3A%22{groupId}%22%20a%3A%22{artifactId}%22"]
image:http://www.javadoc.io/badge/{groupId}/{artifactId}.svg["Javadocs", link="http://www.javadoc.io/doc/{groupId}/{artifactId}"]

Various utilities that complement those found in https://guava.dev/[Guava].

This library focuses on code and API quality, not on performance. Please open an issue if this creates a problem for any of your use cases.
I will make reasonable efforts to respond promptly and fix bugs (or at least document them).

The API is _not_ stable. Please contact me if you are interested in using this library and wonder about stabilizing its API, or if you would like more example code.
The library also uses parts of the Guava API that are https://github.com/google/guava/wiki/UseGuavaInYourBuild#what-if-i-want-to-use-beta-apis-from-a-library-that-people-use-as-a-dependency[marked @Beta] (meaning it is not stable). I will keep the dependencies of this library up-to-date in order to work around any disagreement that this can cause. This means that you need to be committed to update your dependency on this library if Guava’s Beta API changes in order to ensure that you do not run into version conflicts.

The following sections list some of the utilities that this library provides (by package).

== Credentials
https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/credentials/CredentialsReader.html[`CredentialsReader`] permits to read user’s credentials (authentication information) from the system properties, then if not found there, from the environment, then if not found there, from a file.

The focus is on ease of use.

Consider the following code.

[source, java]
----
CredentialsReader<Credentials> reader = CredentialsReader.classicalReader();
Credentials myAuth = reader.getCredentials();
String username = myAuth.API_USERNAME();
String password = myAuth.API_PASSWORD();
----

The first line returns a reader configured to read using the `API_USERNAME` and `API_PASSWORD` system properties or environment variables, or from a file.

Start the software with the https://stackoverflow.com/a/7054981[system properties] `API_USERNAME` set to the value `my username` and `API_PASSWORD` to the value `my password` (for example, using the `-D` command line argument when starting java), and these values will be passed to the variables `username` and `password`.

Assuming that these system properties are not set, but the environment variables `API_USERNAME` and `API_PASSWORD` are set, these variables will then hold the corresponding values.

Assume that neither these system properties nor these environment variables are set, but a file `API_credentials.txt` exists, containing two lines of text: in this case, the returned `myAuth` instance will contain as username the first line of the file, and as password, the second line.

This mechanism is particularly appropriate for developing open source projects, where you do not want the credentials (for example, those used for testing the software) to be committed in the version control system. In such a situation, a classical problem is that such private credentials will also not be directly available from the continuous integration server. To solve this, put the credentials in a file on your own machine, so that they are available while you develop (it is easier and cleaner than configuring environment variables), and store the credentials in environment variables on the continuous integration server (which is usually made easy by the continuous integration web interface). The code above will make your application adapt automatically and find the credentials in both situations. You can also override them manually when starting the application, using system properties, if necessary.

`CredentialsReader` also allows for using more or less than two keys, other keys than `API_USERNAME` and `API_PASSWORD`, and configuring the path to read from.

== Exceptions
Objects to deal with code that declare checked exceptions; or that throw exceptions.

The https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/exceptions/Try.html[`Try`] class permits to call code that you suspect may throw an exception when you’re only interested in storing the result of the call or the exception, rather than desiring that the exception propagates and the control be lost. This is mostly useful when running some code whose correctness you want to test, for example, when grading student’s code. It is a simplified version of, and is heavily inspired by, its Vavr https://www.vavr.io/vavr-docs/[counterpart]. (I https://github.com/oliviercailloux/java-course/blob/main/Libs.adoc[do not use] Vavr personnally because it uses sneaky-throws, but this is only a personal preference.)

For example, having a method in the class `SomeClass` declared as `public static Something getSomething()`, you can use the instruction `Try<Something> t = Try.of(SomeClass::getSomething);`, and `t` will contain either the instance of `Something` that was returned by `getSomething`, or the exception it threw, if it threw an exception.

The https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/exceptions/Unchecker.html[`Unchecker`] class (inspired by https://github.com/diffplug/durian/[Durian]) permits to reduce some annoyances coming with code that throws checked exceptions, in particular, when trying to use such code in lambda expressions. See the following example, where the method `someRunnable` is declared as follows: `void someRunnable() throws SQLException`.

[source, java]
----
void testRunnableDoesNotThrow() {
	Unchecker<SQLException, IllegalStateException> unchecker = Unchecker.wrappingWith(IllegalStateException::new);
	unchecker.call(this::someRunnable);
}
----

Note that calling `someRunnable` normally requires to deal with the (possible) https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/SQLException.html[`SQLException`], as it is a checked exception declared by `someRunnable`. We see that the method `testRunnableDoesNotThrow`, however, does nothing to deal with it, and does not declare it either. This is because the `unchecker` will transform the `SQLException`, if thrown when calling `someRunnable`, into an unchecked exception, here, an `IllegalStateException`. The transformation is done thanks to the wrapper given as a parameter to the `wrappingWith` factory method.

Use directly `Unchecker.link:https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/exceptions/Unchecker.html#IO_UNCHECKER[IO_UNCHECKER]` when desiring to transform https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/IOException.html[`IOException`] instances to https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/UncheckedIOException.html[`UncheckedIOException`] ones.

== GraphUtils
A few static methods to create graphs from other structures such as a set of root nodes and a successor function, and to obtain a set of the nodes of a graph that iterates following a topological sort (thanks to https://github.com/jrtom/jung/pull/174[jbduncan]).

== Xml
A few helper classes to deal with XML, using the DOM (Document Object Model), XSLT, or schema based validation. See the https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/xml/package-summary.html[package documentation].

=== DomHelper
https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/xml/DomHelper.html[`DomHelper`] helps with W3C DOM manipulation, in particular, serialization and deserialization, and provides static methods for manipulating lists of nodes. For example, it provides a method to deal with a list of nodes as a Java `List` rather than the more cumbersome `NodeList` provided by the standard.

I like to use Java’s W3C library for manipulating the DOM because this API is a W3C standard (hence, will be similar in other languages and rests on sounds and clear principles); and it is included in the JRE. That said, its Java implementation is now quite old, as the need for the method `DomHelper#toList` illustrates. So for non-trivial manipulations of XML or HTML documents, you’d probably better use a https://github.com/oliviercailloux/java-course/blob/main/Libs.adoc[more recent library].

=== SchemaHelper
https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/xml/SchemaHelper.html[`SchemaHelper`] helps dealing with XML schema. It provides a method to obtain a `Schema` instance representing a given XML Schema (which may be useful for interacting with the Java XML classes); and one to obtain a document validator for a given XML Schema.

The following example validates a DocBook instance against its schema (note that for DocBook you’d better not use an XSD schema, this is just a silly example).

[source, java]
----
URI docBook = URI.create("https://raw.githubusercontent.com/oliviercailloux/JARiS/main/src/test/resources/io/github/oliviercailloux/jaris/xml/docbook%20simple%20article.xml");
URI docBookSchemaUri = URI.create("https://cdn.docbook.org/schema/5.0.1/xsd/docbook.xsd");

SchemaHelper schemaHelper = SchemaHelper.schemaHelper();
Schema docBookSchema = schemaHelper.asSchema(docBookSchemaUri);
ConformityChecker conformityChecker = schemaHelper.conformityChecker(docBookSchema);

conformityChecker.verifyValid(docBook);
----

The last line will throw an exception iff the document is invalid (it is valid in this example).

=== XmlTransformer
https://www.javadoc.io/doc/io.github.oliviercailloux/jaris/latest/io/github/oliviercailloux/jaris/xml/XmlTransformer.html[`XmlTransformer`] helps transforming XML Documents (including, transforming them to string form).

The following example transforms a DocBook document into a FO document using the DocBook to FO stylesheet. For this to work you need to have an XML library such as Xalan in your class path: this is too complex for the default one provided with the JDK (see this https://github.com/oliviercailloux/JARiS/blob/main/pom.xml[example POM] where Xalan appears as optional dependency).

[source, java]
----
URI docBook = URI.create("https://raw.githubusercontent.com/oliviercailloux/JARiS/master/src/test/resources/io/github/oliviercailloux/jaris/xml/docbook%20simple%20article.xml");
URI docBookStylesheet = URI.create("https://cdn.docbook.org/release/xsl/1.79.2/fo/docbook.xsl");
String transformed = XmlTransformerFactory.usingFactory(KnownFactory.XALAN).usingStylesheet(docBookStylesheet).sourceToChars(docBook);
----

== Nu validator
I have some hopes of using the power of Nu validator to help with validation of HTML files (attempted https://github.com/oliviercailloux/JARiS/commit/a8bfc3d303d268ae844e95b99b0a63005f557050[here]), but this feature is currently blocked by https://github.com/validator/validator/issues/1504[this issue]. 
Please thumb that issue up if this seems of interest.
